### ISSUE TITLE
Consider proposed decorators for ES6 classes

### ISSUE THREAD

**Issue by stefan-pdx** [luhsra/RT.js#3]
There is a [proposal](https://tc39.es/proposal-decorators/) to add support for decorators for ES6 classes. Instead of having to write code like this:

```js
class MyTask extends Task {
    // @rtjs
    *run() {
        var i = 0;
        while (i < 1000000) {
           i++;
        }
        // implement your task here
    }
}
```

RT.js would allow for code to be written as:

```js
class MyTask extends Task {
    @rtjs
    *run() {
        var i = 0;
        while (i < 1000000) {
           i++;
        }
        // implement your task here
    }
}
```

This could be implemented in the short-term using Babel's [@babel/plugin-proposal-decorators](https://babeljs.io/docs/en/babel-plugin-proposal-decorators) plugin.

Please let me know what your thoughts are on this -- I'd like to help out!

**Comment by stettberger** [comment]
We already support decorators like this as well as the comment-style replacement. As these decorators are only used within the transpiler to mark functions that should become preemptable. In the transpiled code, no decorator is needed. Therefore, we do not require the runtime JS interpreter to support decorators.

The corresponding location in the transpiler is `asRTJSFunctionLike()`.
